### ISSUE TITLE
SQL Server VM

### ISSUE THREAD

**Issue by markjones-msft** [happyadam73/tsql-chatgpt#5]
For Completeness - should we offer a SQL BM build with SMSS (any of the SQL Dev images should do it)

**Comment by markjones-msft** [comment]
Or link to SSMS?

**Comment by happyadam73** [comment]
Readme updated to reflect that this will work in SSMS as well as Azure Data Studio - with download links for both applications if required.  Should work in VS Code (but not tested) - doesn't work in Azure Portal Query preview, but this is intended for a client app such as Azure Data Studio or SSMS.
